export const data = [
  { country_name: "AED - United Arab Emirates Dirham", currency: "AED" },
  { country_name: "AFN - Afghan Afghani", currency: "AFN" },
  { country_name: "ALL - Albanian Lek", currency: "ALL" },
  { country_name: "AMD - Armenian Dram", currency: "AMD" },
  { country_name: "ANG - Netherlands Antillean Guilder", currency: "ANG" },
  { country_name: "AOA - Angolan Kwanza", currency: "AOA" },
  { country_name: "ARS - Argentine Peso", currency: "ARS" },
  { country_name: "AUD - Australian Dollar", currency: "AUD" },
  { country_name: "AWG - Aruban Florin", currency: "AWG" },
  { country_name: "AZN - Azerbaijani Manat", currency: "AZN" },
  {
    country_name: "BAM - Bosnia and Herzegovina Convertible Mark",
    currency: "BAM",
  },
  { country_name: "BBD - Barbadian Dollar", currency: "BBD" },
  { country_name: "BDT - Bangladeshi Taka", currency: "BDT" },
  { country_name: "BGN - Bulgarian Lev", currency: "BGN" },
  { country_name: "BHD - Bahraini Dinar", currency: "BHD" },
  { country_name: "BIF - Burundian Franc", currency: "BIF" },
  { country_name: "BMD - Bermudian Dollar", currency: "BMD" },
  { country_name: "BND - Brunei Dollar", currency: "BND" },
  { country_name: "BOB - Bolivian Boliviano", currency: "BOB" },
  { country_name: "BRL - Brazilian Real", currency: "BRL" },
  { country_name: "BSD - Bahamian Dollar", currency: "BSD" },
  { country_name: "BTC - Bitcoin", currency: "BTC" },
  { country_name: "BTN - Bhutanese Ngultrum", currency: "BTN" },
  { country_name: "BWP - Botswanan Pula", currency: "BWP" },
  { country_name: "BYN - Belarusian Ruble", currency: "BYN" },
  { country_name: "BYR - Belarusian Ruble (old)", currency: "BYR" },
  { country_name: "BZD - Belize Dollar", currency: "BZD" },
  { country_name: "CAD - Canadian Dollar", currency: "CAD" },
  { country_name: "CDF - Congolese Franc", currency: "CDF" },
  { country_name: "CHF - Swiss Franc", currency: "CHF" },
  { country_name: "CLF - Chilean Unit of Account (UF)", currency: "CLF" },
  { country_name: "CLP - Chilean Peso", currency: "CLP" },
  { country_name: "CNY - Chinese Yuan", currency: "CNY" },
  { country_name: "CNH - Chinese Yuan (Offshore)", currency: "CNH" },
  { country_name: "COP - Colombian Peso", currency: "COP" },
  { country_name: "CRC - Costa Rican Colón", currency: "CRC" },
  { country_name: "CUC - Cuban Convertible Peso", currency: "CUC" },
  { country_name: "CUP - Cuban Peso", currency: "CUP" },
  { country_name: "CVE - Cape Verdean Escudo", currency: "CVE" },
  { country_name: "CZK - Czech Koruna", currency: "CZK" },
  { country_name: "DJF - Djiboutian Franc", currency: "DJF" },
  { country_name: "DKK - Danish Krone", currency: "DKK" },
  { country_name: "DOP - Dominican Peso", currency: "DOP" },
  { country_name: "DZD - Algerian Dinar", currency: "DZD" },
  { country_name: "EGP - Egyptian Pound", currency: "EGP" },
  { country_name: "ERN - Eritrean Nakfa", currency: "ERN" },
  { country_name: "ETB - Ethiopian Birr", currency: "ETB" },
  { country_name: "EUR - Euro", currency: "EUR" },
  { country_name: "FJD - Fijian Dollar", currency: "FJD" },
  { country_name: "FKP - Falkland Islands Pound", currency: "FKP" },
  { country_name: "GBP - British Pound Sterling", currency: "GBP" },
  { country_name: "GEL - Georgian Lari", currency: "GEL" },
  { country_name: "GGP - Guernsey Pound", currency: "GGP" },
  { country_name: "GHS - Ghanaian Cedi", currency: "GHS" },
  { country_name: "GIP - Gibraltar Pound", currency: "GIP" },
  { country_name: "GMD - Gambian Dalasi", currency: "GMD" },
  { country_name: "GNF - Guinean Franc", currency: "GNF" },
  { country_name: "GTQ - Guatemalan Quetzal", currency: "GTQ" },
  { country_name: "GYD - Guyanaese Dollar", currency: "GYD" },
  { country_name: "HKD - Hong Kong Dollar", currency: "HKD" },
  { country_name: "HNL - Honduran Lempira", currency: "HNL" },
  { country_name: "HRK - Croatian Kuna", currency: "HRK" },
  { country_name: "HTG - Haitian Gourde", currency: "HTG" },
  { country_name: "HUF - Hungarian Forint", currency: "HUF" },
  { country_name: "IDR - Indonesian Rupiah", currency: "IDR" },
  { country_name: "ILS - Israeli New Shekel", currency: "ILS" },
  { country_name: "IMP - Isle of Man Pound", currency: "IMP" },
  { country_name: "INR - Indian Rupee", currency: "INR" },
  { country_name: "IQD - Iraqi Dinar", currency: "IQD" },
  { country_name: "IRR - Iranian Rial", currency: "IRR" },
  { country_name: "ISK - Icelandic Króna", currency: "ISK" },
  { country_name: "JEP - Jersey Pound", currency: "JEP" },
  { country_name: "JMD - Jamaican Dollar", currency: "JMD" },
  { country_name: "JOD - Jordanian Dinar", currency: "JOD" },
  { country_name: "JPY - Japanese Yen", currency: "JPY" },
  { country_name: "KES - Kenyan Shilling", currency: "KES" },
  { country_name: "KGS - Kyrgystani Som", currency: "KGS" },
  { country_name: "KHR - Cambodian Riel", currency: "KHR" },
  { country_name: "KMF - Comorian Franc", currency: "KMF" },
  { country_name: "KPW - North Korean Won", currency: "KPW" },
  { country_name: "KRW - South Korean Won", currency: "KRW" },
  { country_name: "KWD - Kuwaiti Dinar", currency: "KWD" },
  { country_name: "KYD - Cayman Islands Dollar", currency: "KYD" },
  { country_name: "KZT - Kazakhstani Tenge", currency: "KZT" },
  { country_name: "LAK - Laotian Kip", currency: "LAK" },
  { country_name: "LBP - Lebanese Pound", currency: "LBP" },
  { country_name: "LKR - Sri Lankan Rupee", currency: "LKR" },
  { country_name: "LRD - Liberian Dollar", currency: "LRD" },
  { country_name: "LSL - Lesotho Loti", currency: "LSL" },
  { country_name: "LTL - Lithuanian Litas", currency: "LTL" },
  { country_name: "LVL - Latvian Lats", currency: "LVL" },
  { country_name: "LYD - Libyan Dinar", currency: "LYD" },
  { country_name: "MAD - Moroccan Dirham", currency: "MAD" },
  { country_name: "MDL - Moldovan Leu", currency: "MDL" },
  { country_name: "MGA - Malagasy Ariary", currency: "MGA" },
  { country_name: "MKD - Macedonian Denar", currency: "MKD" },
  { country_name: "MMK - Myanmar Kyat", currency: "MMK" },
  { country_name: "MNT - Mongolian Tugrik", currency: "MNT" },
  { country_name: "MOP - Macanese Pataca", currency: "MOP" },
  { country_name: "MRU - Mauritanian Ouguiya", currency: "MRU" },
  { country_name: "MUR - Mauritian Rupee", currency: "MUR" },
  { country_name: "MVR - Maldivian Rufiyaa", currency: "MVR" },
  { country_name: "MWK - Malawian Kwacha", currency: "MWK" },
  { country_name: "MXN - Mexican Peso", currency: "MXN" },
  { country_name: "MYR - Malaysian Ringgit", currency: "MYR" },
  { country_name: "MZN - Mozambican Metical", currency: "MZN" },
  { country_name: "NAD - Namibian Dollar", currency: "NAD" },
  { country_name: "NGN - Nigerian Naira", currency: "NGN" },
  { country_name: "NIO - Nicaraguan Córdoba", currency: "NIO" },
  { country_name: "NOK - Norwegian Krone", currency: "NOK" },
  { country_name: "NPR - Nepalese Rupee", currency: "NPR" },
  { country_name: "NZD - New Zealand Dollar", currency: "NZD" },
  { country_name: "OMR - Omani Rial", currency: "OMR" },
  { country_name: "PAB - Panamanian Balboa", currency: "PAB" },
  { country_name: "PEN - Peruvian Sol", currency: "PEN" },
  { country_name: "PGK - Papua New Guinean Kina", currency: "PGK" },
  { country_name: "PHP - Philippine Peso", currency: "PHP" },
  { country_name: "PKR - Pakistani Rupee", currency: "PKR" },
  { country_name: "PLN - Polish Złoty", currency: "PLN" },
  { country_name: "PYG - Paraguayan Guarani", currency: "PYG" },
  { country_name: "QAR - Qatari Rial", currency: "QAR" },
  { country_name: "RON - Romanian Leu", currency: "RON" },
  { country_name: "RSD - Serbian Dinar", currency: "RSD" },
  { country_name: "RUB - Russian Ruble", currency: "RUB" },
  { country_name: "RWF - Rwandan Franc", currency: "RWF" },
  { country_name: "SAR - Saudi Riyal", currency: "SAR" },
  { country_name: "SBD - Solomon Islands Dollar", currency: "SBD" },
  { country_name: "SCR - Seychellois Rupee", currency: "SCR" },
  { country_name: "SDG - Sudanese Pound", currency: "SDG" },
  { country_name: "SEK - Swedish Krona", currency: "SEK" },
  { country_name: "SGD - Singapore Dollar", currency: "SGD" },
  { country_name: "SHP - Saint Helena Pound", currency: "SHP" },
  { country_name: "SLE - Sierra Leonean Leone", currency: "SLE" },
  { country_name: "SLL - Sierra Leonean Leone (old)", currency: "SLL" },
  { country_name: "SOS - Somali Shilling", currency: "SOS" },
  { country_name: "SRD - Surinamese Dollar", currency: "SRD" },
  { country_name: "STD - São Tomé and Príncipe Dobra", currency: "STD" },
  { country_name: "SVC - Salvadoran Colón", currency: "SVC" },
  { country_name: "SYP - Syrian Pound", currency: "SYP" },
  { country_name: "SZL - Swazi Lilangeni", currency: "SZL" },
  { country_name: "THB - Thai Baht", currency: "THB" },
  { country_name: "TJS - Tajikistani Somoni", currency: "TJS" },
  { country_name: "TMT - Turkmenistani Manat", currency: "TMT" },
  { country_name: "TND - Tunisian Dinar", currency: "TND" },
  { country_name: "TOP - Tongan Paʻanga", currency: "TOP" },
  { country_name: "TRY - Turkish Lira", currency: "TRY" },
  { country_name: "TTD - Trinidad and Tobago Dollar", currency: "TTD" },
  { country_name: "TWD - New Taiwan Dollar", currency: "TWD" },
  { country_name: "TZS - Tanzanian Shilling", currency: "TZS" },
  { country_name: "UAH - Ukrainian Hryvnia", currency: "UAH" },
  { country_name: "UGX - Ugandan Shilling", currency: "UGX" },
  { country_name: "USD - US Dollar", currency: "USD" },
  { country_name: "UYU - Uruguayan Peso", currency: "UYU" },
  { country_name: "UZS - Uzbekistani Som", currency: "UZS" },
  { country_name: "VES - Venezuelan Bolívar Soberano", currency: "VES" },
  { country_name: "VND - Vietnamese Dong", currency: "VND" },
  { country_name: "VUV - Vanuatu Vatu", currency: "VUV" },
  { country_name: "WST - Samoan Tala", currency: "WST" },
  { country_name: "XAF - Central African CFA Franc", currency: "XAF" },
  { country_name: "XAG - Silver (troy ounce)", currency: "XAG" },
  { country_name: "XAU - Gold (troy ounce)", currency: "XAU" },
  { country_name: "XCD - East Caribbean Dollar", currency: "XCD" },
  { country_name: "XDR - IMF Special Drawing Rights", currency: "XDR" },
  { country_name: "XOF - West African CFA Franc", currency: "XOF" },
  { country_name: "XPF - CFP Franc", currency: "XPF" },
  { country_name: "YER - Yemeni Rial", currency: "YER" },
  { country_name: "ZAR - South African Rand", currency: "ZAR" },
  { country_name: "ZMK - Zambian Kwacha (old)", currency: "ZMK" },
  { country_name: "ZMW - Zambian Kwacha", currency: "ZMW" },
  { country_name: "ZWL - Zimbabwean Dollar", currency: "ZWL" },
];
